name: Continious integration

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Assemble runtime
        run: ./gradlew :kotlinx-serialization-runtime:assemble
